server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Cấu hình này cực kỳ quan trọng cho React Router (Tránh lỗi 404 khi F5)
        try_files $uri $uri/ /index.html;
    }
}
